/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper */

#ifndef _Included_com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper
#define _Included_com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper
 * Method:    getResult
 * Signature: (Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper_getResult
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper_clean
  (JNIEnv *, jobject);

/*
 * Class:     com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper
 * Method:    graphBuilder
 * Signature: ([DLjava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_edu_fersko_smartcalc_models_SmartCalcJNIWrapper_graphBuilder
  (JNIEnv *, jobject, jdoubleArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
