/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_fersko_smartcalc_models_CreditModelJNIWrapper */
#include "core/creditCalculator/creditModel.h"

#ifndef _Included_com_edu_fersko_smartcalc_models_CreditModelJNIWrapper
#define _Included_com_edu_fersko_smartcalc_models_CreditModelJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edu_fersko_smartcalc_models_CreditModelJNIWrapper
 * Method:    annuityNative
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_edu_fersko_smartcalc_models_CreditModelJNIWrapper_annuity
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_edu_fersko_smartcalc_models_CreditModelJNIWrapper
 * Method:    deffirentated
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_edu_fersko_smartcalc_models_CreditModelJNIWrapper_deffirentated
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_edu_fersko_smartcalc_models_CreditModelJNIWrapper
 * Method:    getResult
 * Signature: ()Lcom/edu/fersko/smartcalc/models/CreditData;
 */
JNIEXPORT jobject JNICALL Java_com_edu_fersko_smartcalc_models_CreditModelJNIWrapper_getResult
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
