/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edu_fersko_smartcalc_models_RPN */
#include "smartCalc.h"

#ifndef _Included_com_edu_fersko_smartcalc_models_RPN
#define _Included_com_edu_fersko_smartcalc_models_RPN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edu_fersko_smartcalc_models_RPN
 * Method:    getResult
 * Signature: (Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_com_edu_fersko_smartcalc_models_RPN_getResult
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_edu_fersko_smartcalc_models_RPN
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_edu_fersko_smartcalc_models_RPN_clean
  (JNIEnv *, jobject);

JNIEXPORT jobjectArray JNICALL Java_com_edu_fersko_smartcalc_models_RPN_graphBuilder
  (JNIEnv *env, jobject obj, jdoubleArray jData, jstring jstr);

#ifdef __cplusplus
}
#endif
#endif
